name: Build artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v: ['0.28.0', '0.29.0', '0.30.0', '0.31.0', '0.32.0', '0.33.0']
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/midnightntwrk/compact/releases/latest/download/compact-installer.sh | sh
          export PATH=$HOME/.local/bin:$HOME/.compact/bin:$PATH
          compact update ${{ matrix.v }} || exit 0
          compact compile preprod-deployment/contracts/src/bboard.compact ./managed
      - uses: actions/upload-artifact@v4
        with:
          name: contract-${{ matrix.v }}
          path: ./managed
